import { chromium, SP, getKey, tester, BASE, DATA, FIXTURES } from '../lib.mjs';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
const { errors, ok, W, pick, back } = tester(page);
await page.goto(`${BASE}/`); await W();
await pick('설정');
const vbox = page.locator('div.bg-blue-50').first();
const ark = vbox.locator('[data-test-row="ARK"]');
await ark.getByRole('button', { name: /자세히/ }).click(); await W(200);
await ark.getByRole('button', { name: '검사 삭제' }).click(); await W(200);
await ark.getByRole('button', { name: /한 번 더/ }).click(); await W(200);
await page.getByRole('button', { name: '저장', exact: true }).click(); await W(800);
await page.reload(); await W(1200);
await pick('설정');
ok(await page.locator('div.bg-blue-50').first().locator('[data-test-row="ARK"]').count() === 0, 'ARK 삭제 후 다시 생기지 않음');
const st = (await getKey('settings')).value;
ok(!st.tests.some(t => t.id === 'ark') && st.arkRemoved === true, '저장됨');
ok(await page.getByRole('button', { name: '메인 화면' }).count() === 1 && await page.getByText('화면 전환').count() === 0, "'메인 화면' 버튼, '화면 전환' 없음");
ok(errors.length === 0, `페이지 오류 없음 ${errors.join(' / ')}`);
await browser.close();
