import { chromium, SP, getKey, editKey, tester, BASE, measureVision } from '../lib.mjs';
// History: 시력방은 초진에게 설문지만 드리고([History 설문지 드리기]), 입력은 처치실(검사 지정 대기)에서
await editKey('daily-patients', list => list.map(p => (p.name === '최민지' || p.name === '정대현' ? { ...p, firstVisit: true } : p)));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
const { errors, ok, W, pick, back, cardOf } = tester(page);
await page.goto(`${BASE}/`); await W(1000);
await pick('시력');
ok(await cardOf('최민지').getByRole('button', { name: 'History 설문지 드리기' }).count() === 1, '초진 → [History 설문지 드리기]');
ok(await cardOf('최민지').getByRole('button', { name: /History (입력|필요|수정)/ }).count() === 0, '시력방에는 History 입력 버튼·창 없음');
// 강서윤(초진): 측정만 하면 설문지가 남아 시력방에 그대로
await measureVision(page, cardOf('강서윤'), '0.5');
let k = (await getKey('daily-patients')).value.find(p => p.name === '강서윤');
ok(!k.done?.visionIop && k.measureOk && k.vaOk && k.nctOk, '시력·NCT 따로 저장 → 측정 완료, 설문지 남아 시력방에 그대로');
await cardOf('강서윤').screenshot({ path: `${SP}/r29-measure-done.png` });
await cardOf('강서윤').getByRole('button', { name: '측정값 수정' }).click(); await W(300);
ok(await page.locator('.fixed.inset-0').count() === 1, '[수정]으로 측정 창');
await page.locator('.fixed.inset-0').last().getByRole('button', { name: '취소', exact: true }).click(); await W(300);
await cardOf('강서윤').getByRole('button', { name: 'History 설문지 드리기' }).click(); await W(1500);
k = (await getKey('daily-patients')).value.find(p => p.name === '강서윤');
ok(k.done?.visionIop === true && k.hxSheetAt && !k.hx, '설문지 드림 → 시력방 자동 완료 (History는 아직 없음)');
ok(await page.getByText(/강서윤 시력방 완료/).count() === 1, '완료 알림');
await back();
// 처치실 검사 지정 대기: [History 입력] (검사 지정과 같은 줄)
await pick('처치실');
const tc = cardOf('강서윤');
const hb = await tc.getByRole('button', { name: '강서윤 History 입력' }).boundingBox();
const ab = await tc.getByRole('button', { name: '검사 지정', exact: true }).boundingBox();
ok(hb && ab && Math.abs(hb.y - ab.y) < 4 && Math.abs(hb.height - ab.height) < 2 && hb.x < ab.x, '처치실: [History 입력]·[검사 지정] 같은 줄, 같은 크기, 왼쪽부터');
ok(!/오늘 검사\s*없음/.test(await tc.innerText()), "'오늘 검사 없음' 줄 없음");
await tc.getByRole('button', { name: '강서윤 History 입력' }).click(); await W(300);
const m = page.locator('.fixed.inset-0').last();
await m.getByRole('button', { name: '고혈압 있음' }).click();
await m.getByRole('button', { name: '당뇨 있음' }).click();
await m.getByLabel('당뇨 기간').fill('5');
await m.getByLabel('주호소').fill('좌안 흐림 1달');
await m.screenshot({ path: `${SP}/r18-hx-modal.png` });
await m.getByRole('button', { name: '확인', exact: true }).click(); await W();
k = (await getKey('daily-patients')).value.find(p => p.name === '강서윤');
ok(k.hx?.dm === true && k.hx.dmYears === '5' && k.hx.cc === '좌안 흐림 1달', '처치실에서 History 입력 → 그날 환자 기록에 저장');
ok(/주호소/.test(await cardOf('강서윤').innerText()), '입력 후 카드에 History');
ok((await getKey('patient-history')).value === null, '미리 채우기 저장소에 쓰지 않음');
ok(errors.length === 0, `페이지 오류 없음 ${errors.join(' / ')}`);
await browser.close();
