import { execSync } from 'child_process';
import fs from 'fs';
import { chromium, SP, DATA, BASE, FIXTURES } from '../lib.mjs';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
const ok = (c, m) => { console.log(`${c ? 'OK  ' : 'FAIL'} ${m}`); if (!c) process.exitCode = 1; };
const wait = (ms = 500) => page.waitForTimeout(ms);
const openSettings = async () => { await page.getByRole('button', { name: /^설정/ }).first().click(); await wait(700); };
const back = async () => { await page.getByRole('button', { name: '메인 화면' }).click(); await wait(300); };
const inSettings = () => page.getByRole('button', { name: '기타', exact: true }).count();
await page.goto(`${BASE}/`); await wait();
await openSettings();
ok(await inSettings() === 1, '비밀번호 없으면 바로 들어감');
await page.getByRole('button', { name: '기타', exact: true }).click(); await wait(300);
await page.getByLabel('새 비밀번호', { exact: true }).fill('1234');
await page.getByLabel('새 비밀번호 확인').fill('1235');
await page.getByRole('button', { name: '비밀번호 저장', exact: true }).click(); await wait(300);
ok(await page.getByText('새 비밀번호 두 칸이 다릅니다').count() === 1, '확인 칸 다르면 거절');
await page.getByLabel('새 비밀번호 확인').fill('1234');
await page.getByRole('button', { name: '비밀번호 저장', exact: true }).click(); await wait(600);
ok(/사용 중/.test(await page.locator('div.font-medium', { hasText: /^설정 비밀번호/ }).innerText()), '저장 → 사용 중');
const lock = fs.readFileSync(`${DATA}/settings-lock.json`, 'utf8');
ok(!lock.includes('1234') && /"hash"/.test(lock), '평문 저장 안 됨 (해시)');
ok(!fs.existsSync(`${DATA}/keys/settings-lock.json`), '공유 저장소에는 없음');
const leak = await fetch(`${BASE}/api/storage/settings-lock`);
ok(leak.status === 404, '저장소 주소로 읽을 수 없음');
await page.screenshot({ path: `${SP}/r11-card.png`, clip: { x: 300, y: 100, width: 766, height: 260 } });
await back();
await openSettings();
ok(await page.getByText('설정 비밀번호', { exact: true }).count() === 1 && await inSettings() === 0, '다시 들어가면 비밀번호 창');
await page.screenshot({ path: `${SP}/r11-modal.png` });
await page.getByLabel('설정 비밀번호').fill('0000'); await page.getByRole('button', { name: '확인' }).click(); await wait(1300);
ok(await page.getByText('비밀번호가 틀렸습니다').count() === 1 && await inSettings() === 0, '틀린 비밀번호 거부');
await page.getByLabel('설정 비밀번호').fill('1234'); await page.keyboard.press('Enter'); await wait(800);
ok(await inSettings() === 1, '맞는 비밀번호로 들어감');
// 변경: 현재 비밀번호 틀림 → 거절
await page.getByRole('button', { name: '기타', exact: true }).click(); await wait(300);
await page.getByLabel('현재 비밀번호', { exact: true }).fill('9999');
await page.getByLabel('새 비밀번호', { exact: true }).fill('abcd'); await page.getByLabel('새 비밀번호 확인').fill('abcd');
await page.getByRole('button', { name: '비밀번호 저장', exact: true }).click(); await wait(1300);
ok(await page.getByText('현재 비밀번호가 틀렸습니다').count() === 1, '현재 비밀번호 틀리면 변경 거절');
await page.getByLabel('현재 비밀번호', { exact: true }).fill('1234');
await page.getByRole('button', { name: '비밀번호 저장', exact: true }).click(); await wait(600);
ok(await page.getByText('비밀번호를 저장했습니다').count() === 1, '변경됨');
await page.getByLabel('현재 비밀번호', { exact: true }).fill('abcd');
await page.getByRole('button', { name: '비밀번호 없애기', exact: true }).click(); await wait(600);
ok(/사용 안 함/.test(await page.locator('div.font-medium', { hasText: /^설정 비밀번호/ }).innerText()), '없애기');
await back(); await openSettings();
ok(await inSettings() === 1, '없앤 뒤 바로 들어감');
// 초기화 bat 흉내: 파일 삭제
await page.getByRole('button', { name: '기타', exact: true }).click(); await wait(300);
await page.getByLabel('새 비밀번호', { exact: true }).fill('7777'); await page.getByLabel('새 비밀번호 확인').fill('7777');
await page.getByRole('button', { name: '비밀번호 저장', exact: true }).click(); await wait(600);
fs.unlinkSync(`${DATA}/settings-lock.json`);
await back(); await openSettings();
ok(await inSettings() === 1, '초기화(파일 삭제) 후 바로 들어감, 서버 재시작 없이');
ok(errors.length === 0, '페이지 오류 없음');
await browser.close();
