import { chromium, SP, getKey, editKey, tester, BASE, DATA, FIXTURES } from '../lib.mjs';
await editKey('settings', s => {
  const rooms = s.rooms.some(r => r.builtin === 'treat') ? s.rooms : [...s.rooms, { id: 'treat', name: '처치실', patientName: '처치실', showPriority: false, builtin: 'treat' }];
  return { ...s, rooms, tests: [...s.tests, { id: 'osdi', name: 'OSDI 설문', short: 'OSDI', roomId: 'treat', order: 0, options: [], popupOnClick: false, machine: '', withExams: true }] };
});
await editKey('daily-patients', list => list.map(p => (p.name === '서준호' ? { ...p, assigned: { ...p.assigned, osdi: true }, done: { ...p.done, osdi: false } } : p)));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
const { errors, ok, W, pick, back, cardOf } = tester(page);
await page.goto(`${BASE}/`); await W();
await pick('처치실');
ok(await cardOf('서준호').getByRole('button', { name: '처방 전', exact: true }).count() === 1, '처음엔 OSDI도 처방 전');
await back();
// 설정: OSDI 처방 필요 없음 + History 양식 항목 추가
await pick('설정');
const osdiBlock = page.locator('[data-test-row="OSDI"]');
await osdiBlock.getByRole('button', { name: '처방 없음', exact: true }).click();
await page.getByRole('button', { name: '기타', exact: true }).click(); await W(300);
await page.getByRole('button', { name: '항목 추가' }).click(); await W(200);
await page.getByLabel('History 항목 이름').last().fill('녹내장 가족력');
await page.getByLabel('History 요약 이름').last().fill('FHx 녹내장');
await page.getByLabel('History 항목 형식').last().selectOption('yn');
await page.screenshot({ path: `${SP}/r20-hx-settings.png`, fullPage: true });
await page.getByRole('button', { name: '저장', exact: true }).click(); await W(800);
await back();
await pick('처치실');
ok(await cardOf('서준호').getByRole('button', { name: '처방 전', exact: true }).count() === 0, 'OSDI 처방 필요 없음 → 처방 전 표시 없음');
await back();
await editKey('daily-patients', list => list.map(p => (p.name === '최민지' ? { ...p, firstVisit: true } : p)));
await W(4500);
await pick('시력');
await cardOf('최민지').getByRole('button', { name: /^History (입력|필요)$/ }).click(); await W(300);
const m = page.locator('.fixed.inset-0').last();
ok(await m.getByRole('button', { name: '녹내장 가족력 있음' }).count() === 1, 'History 창에 추가한 항목');
ok(await m.locator('textarea[aria-label="이전 안과 수술력"]').count() === 1, '안과 수술력은 여러 줄 글');
await m.getByRole('button', { name: '녹내장 가족력 있음' }).click();
await m.getByRole('button', { name: '확인', exact: true }).click(); await W();
ok(await cardOf('최민지').getByText(/FHx 녹내장\(\+\)/).count() === 1, '요약에 요약 이름으로 표시');
await m.screenshot({ path: `${SP}/r20-hx-modal.png` }).catch(() => {});
ok(errors.length === 0, `페이지 오류 없음 ${errors.join(' / ')}`);
await browser.close();
