import { chromium, SP, getKey, editKey, tester, BASE, DATA, FIXTURES } from '../lib.mjs';
await editKey('daily-patients', list => list.map(p => (p.name === '윤지아' || p.name === '조현우' ? { ...p, dilateOverride: true } : p)));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
const { errors, ok, W, pick, back, cardOf } = tester(page);
await page.goto(`${BASE}/`); await W(1000);
await pick('31번방');
let y = cardOf('윤지아');
ok(await y.getByText(/VF 끝난 뒤/).count() === 1 && await y.getByRole('button', { name: /^산동/ }).count() === 0, 'VF 남은 환자: 점안 막힘');
await y.screenshot({ path: `${SP}/r21-vf-block.png` });
ok(await cardOf('조현우').getByRole('button', { name: '산동', exact: true }).count() === 1, 'VF 없는 환자는 점안 가능');
await y.getByRole('button', { name: '▶ 시작' }).click(); await W();
await y.getByRole('button', { name: '종료', exact: true }).click(); await W();
ok(await cardOf('윤지아').getByRole('button', { name: '산동', exact: true }).count() === 1, 'VF 끝나면 점안 가능');
await back();
// 설정: 칩 + 설명 한 번, WFP 산동 금지
await pick('설정');
ok(await page.getByText('도움말 · 검사 옵션 설명').count() === 1, '옵션 설명 한 곳');
ok(await page.getByText("처방이 필요 없는 검사 (예: OSDI). '처방 전' 표시를 하지 않음").count() <= 1, '설명 반복 없음');
const vfBlock = page.locator('[data-test-row="VF"]');
ok(await vfBlock.getByRole('button', { name: /산동 금지/ }).getAttribute('aria-pressed') === 'true', 'VF는 기본 산동 금지');
const wfp = page.locator('[data-test-row="WFP"]');
await wfp.getByRole('button', { name: /산동 금지/ }).click();
await wfp.screenshot({ path: `${SP}/r21-chips.png` });
await page.getByRole('button', { name: '저장', exact: true }).click(); await W(800);
await back();
await pick('31번방');
ok(await cardOf('조현우').getByText(/WFP 끝난 뒤/).count() === 1, '설정에서 WFP 산동 금지 → 점안 막힘');
ok(errors.length === 0, `페이지 오류 없음 ${errors.join(' / ')}`);
await browser.close();
