import { chromium, SP, getKey, editKey, tester, BASE, DATA, FIXTURES } from '../lib.mjs';
await editKey('daily-patients', list => list.map(p => {
  if (p.name === '최민지') return { ...p, firstVisit: true, hx: { htn: true, cc: '아파서 중간내원' } };
  if (p.name === '정대현') return { ...p, firstVisit: true };
  return p;
}));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 768 } });
const { errors, ok, W, pick, back, cardOf } = tester(page);
await page.goto(`${BASE}/`); await W(1000);
await pick('시력');
let c = cardOf('최민지');
ok(await c.getByText('초진', { exact: true }).count() === 1, '초진 표시는 한 번만');
ok(await c.getByText(/이전 값 없음/).count() === 0, '이전 값 없음 줄 숨김');
// 10-07: 오늘 검사는 이름만 작게 보이고, 바꾸기 칸은 [변경]을 눌러야 펼쳐짐
ok(await c.getByRole('button', { name: '오늘 검사 변경' }).count() === 1 && await c.getByRole('button', { name: /WFP/ }).count() === 0, "'오늘 검사' 바꾸기 칸은 접혀 있음 (이름만 작게)");
const mb = await c.getByRole('button', { name: '시력', exact: true }).boundingBox();
const nb = await c.getByRole('button', { name: 'NCT', exact: true }).boundingBox();
const cb = await c.getByRole('button', { name: '접수 취소' }).boundingBox();
ok(Math.abs(mb.y - nb.y) < 4 && Math.abs(mb.y + mb.height / 2 - (cb.y + cb.height / 2)) < 12, '[시력]·[NCT]·접수 취소 한 줄');
ok(await c.getByRole('button', { name: /History/ }).count() === 0 && await c.getByText(/HTN/).count() === 0, 'History가 있으면 시력방에는 아무것도 안 보임 (입력은 처치실)');
c = cardOf('정대현');
ok(await c.getByRole('button', { name: 'History 설문지 드리기', exact: true }).count() === 1, "초진: [History 설문지 드리기] 하나");
await c.screenshot({ path: `${SP}/r25-vision-need.png` });
await cardOf('최민지').screenshot({ path: `${SP}/r25-vision-hx.png` });
// 초진 ↔ 재진
await c.getByRole('button', { name: '초진', exact: true }).click(); await W();
ok((await getKey('daily-patients')).value.find(p => p.name === '정대현').firstVisit === false, '이름 옆 초진 누르면 재진');
await cardOf('정대현').getByRole('button', { name: '재진', exact: true }).click(); await W();
await back();
await pick('31번방');
c = cardOf('윤지아');
ok(await c.getByText('오늘 검사').count() === 0, '검사실: 오늘 검사 줄 없음');
const vf = await c.getByRole('button', { name: '▶ 시작' }).boundingBox();
const chg = await c.getByRole('button', { name: '검사 변경' }).boundingBox();
ok(Math.abs(vf.y + vf.height / 2 - (chg.y + chg.height / 2)) < 12, '[검사 변경]이 검사 칸 줄 끝');
await c.getByRole('button', { name: '검사 변경' }).click(); await W(200);
ok(await c.getByText('오늘 검사').count() === 1 && await c.getByRole('button', { name: '접기' }).count() === 1, '펼치면 오늘 검사 전체');
await c.getByRole('button', { name: '접기' }).click(); await W(200);
c = cardOf('장민호');
ok(await c.getByText(/이전 안압 없음|오늘 안압 없음/).count() === 0, '안압 없음 줄 숨김');
await c.screenshot({ path: `${SP}/r25-room-card.png` });
await back();
await pick('관리자');
await page.getByRole('button', { name: '명단 관리', exact: true }).click(); await W();
c = page.locator('div.bg-white.rounded-xl').filter({ has: page.getByText('원성옥', { exact: true }) }).first();
ok(await c.getByText(/이전 시력 없음/).count() === 0, '관리자: 이전 시력 없음 문구 없음');
const pb = await c.getByRole('button', { name: '이전 시력 입력' }).boundingBox();
const kb = await c.getByRole('button', { name: '접수 안내 추가' }).boundingBox();
ok(Math.abs(pb.y - kb.y) < 12, '이전 시력 입력·접수 안내·진료 전 처치 한 줄');
await c.screenshot({ path: `${SP}/r25-admin-card.png` });
ok(errors.length === 0, `페이지 오류 없음 ${errors.join(' / ')}`);
await browser.close();
