import { execSync } from 'child_process';
import { chromium, SP, DATA, BASE, FIXTURES } from '../lib.mjs';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
const ok = (c, m) => { console.log(`${c ? 'OK  ' : 'FAIL'} ${m}`); if (!c) process.exitCode = 1; };
await page.goto(`${BASE}/`); await page.waitForTimeout(500);
await page.getByRole('button', { name: /^31번방/ }).first().click(); await page.waitForTimeout(500);
const c = page.locator('div.bg-white').filter({ has: page.getByText('윤지아', { exact: true }) }).last();
const b = c.getByRole('button', { name: '처방 전', exact: true });
const bb = await b.boundingBox();
await c.screenshot({ path: `${SP}/r7-before.png` });
await b.click(); await page.waitForTimeout(400);
const d = c.getByText('처방 완료', { exact: true });
ok(await d.count() === 1, '처방 완료 (시각 없음)');
const db = await d.boundingBox();
console.log(`     처방 전 ${bb.width.toFixed(0)}x${bb.height.toFixed(0)}, 처방 완료 ${db.width.toFixed(0)}x${db.height.toFixed(0)}`);
await c.screenshot({ path: `${SP}/r7-after.png` });
await c.getByRole('button', { name: '처방 완료 취소' }).click(); await page.waitForTimeout(400);
ok(await c.getByRole('button', { name: '처방 전', exact: true }).count() === 1, '↺ 취소 동작');
ok(errors.length === 0, '페이지 오류 없음');
await browser.close();
