import fs from 'fs';
import { execSync } from 'child_process';
import { chromium, SP, DATA, BASE, FIXTURES } from '../lib.mjs';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
const ok = (c, m) => { console.log(`${c ? 'OK  ' : 'FAIL'} ${m}`); if (!c) process.exitCode = 1; };
const wait = (ms = 700) => page.waitForTimeout(ms);
await page.goto(`${BASE}/`); await wait();
await page.getByRole('button', { name: /^관리자/ }).first().click(); await wait();
const tomorrow = new Date(Date.now() + 86400000).toLocaleDateString('sv-SE');
await page.locator('input[type=date]').first().fill(tomorrow);
await page.locator('input[type=file]').setInputFiles(`${FIXTURES}/ocs-similar.xlsx`); await wait();
ok(await page.getByText('"예약", "초재진" 칸이 없어 등록하지 않았습니다', { exact: false }).count() === 1, '"예약시간", "초/재진" 제목은 인정 안 하고 파일 전체 등록 안 함');
ok(!JSON.parse(JSON.parse(fs.readFileSync(`${DATA}/keys/daily-patients.json`, 'utf8')).value).some(p => p.id === '0012348'), '그 파일 환자는 등록 안 됨');
await page.locator('input[type=file]').setInputFiles(`${FIXTURES}/ocs-ok.xlsx`); await wait(1000);
const list = JSON.parse(JSON.parse(fs.readFileSync(`${DATA}/keys/daily-patients.json`, 'utf8')).value).filter(p => p.date === tomorrow);
const a = list.find(p => p.id === '0012345');
ok(a && !a.firstVisit && a.doctor === '김선웅' && a.reservation === '09:00', '"구분"(초진) 칸은 무시하고 초재진(재진) 칸 사용');
ok(!('보훈' in a) && !JSON.stringify(a).includes('H40'), '진단명·보훈은 저장 안 함');
ok(!list.some(p => p.id === '0012346'), '안과특수검사 등록 안 함');
ok(list.find(p => p.id === '0012347')?.firstVisit === true, '"진료의 "(뒤 띄어쓰기) 제목과 "나상훈 교수" 인식');
ok(errors.length === 0, '페이지 오류 없음');
await browser.close();
